# dcgm的service monitor
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nvidia-dcgm-exporter
  namespace: monitoring
  labels:
    app: nvidia-dcgm-exporter
    release: prometheus # prometheus发现serviceMonitor的方式
spec:
  endpoints:
  - interval: 1s
    path: /metrics
    port: gpu-metrics
  selector:
    matchLabels:
      app: nvidia-dcgm-exporter
  namespaceSelector:
    matchNames:
      - nvidia-gpu-operator
