# nginx-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: crater-web-frontend
  namespace: {{ .Release.Namespace }}
  labels:
    app: crater-web-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: crater-web-frontend
  template:
    metadata:
      labels:
        app: crater-web-frontend
    spec:
      containers:
        - name: crater-web-frontend-container
          image: {{ .Values.web.frontend.image.repository }}:{{ .Values.web.frontend.image.tag }}
          imagePullPolicy: {{ .Values.web.frontend.image.pullPolicy }}
          ports:
            - containerPort: 80
      nodeSelector: {{ .Values.nodeSelector | toYaml | nindent 8 }}
      tolerations: {{ .Values.tolerations | toYaml | nindent 8 }}