apiVersion: v1
kind: Service
metadata:
  name: crater-web-frontend-svc
  namespace: crater
spec:
  selector:
    app: crater-web-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
