apiVersion: v1
kind: Pod
metadata:
  name: img2img-train
  namespace: user-zkr
spec:
  # securityContext:
  #   runAsUser: 1005 # 运行容器的用户 zhuangkr
  #   runAsGroup: 0 # 容器进程运行的组
  #   fsGroup: 100 # 创建文件目录用的组
  containers:
    - name: main
      # image: jupyter/tensorflow-notebook:latest
      # image: nvidia/cuda:12.2.0-base-ubuntu22.04
      image: wangjh666/image2image:2.5
      workingDir: /workspace
      resources:
        limits:
          cpu: "10"
          memory: 20Gi
          nvidia.com/gpu: 1
        requests:
          cpu: "10"
          memory: 20Gi
          nvidia.com/gpu: 1
      volumeMounts:
        - name: user-volume
          mountPath: /home/zkr
        - name: cache-volume
          mountPath: /dev/shm
        - name: data-volume
          mountPath: /data
      command:
        - "/bin/bash"
        - "-c"
        - |
          # export PATH=/miniconda/bin:${PATH}
          # source /miniconda/etc/profile.d/conda.sh
          # sleep inf
          # PATH=/miniconda/bin:${PATH}
          # source /miniconda/etc/profile.d/conda.sh
          source activate img2img
          # cd /home/shared/ai_training_job/image2image
          python train.py --dataroot /data/img2img/maps --name maps_cyclegan --model cycle_gan --pool_size 50 --no_dropout --display_id 0
          # python train.py --dataroot /data/img2img/facades --name facades_pix2pix --model pix2pix --netG unet_256 --direction BtoA --lambda_L1 100 --dataset_mode aligned --norm batch --pool_size 0 --display_id 0
  restartPolicy: Never
  volumes:
    - name: cache-volume
      emptyDir:
        medium: Memory
    - name: user-volume # home目录
      persistentVolumeClaim:
        claimName: home-zkr-pvc
    - name: data-volume # 数据目录
      persistentVolumeClaim:
        claimName: data-pvc
  nodeSelector: # 添加节点选择器
    kubernetes.io/hostname: dell-68
