apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: home-{zkr}-pvc
  namespace: user-{zkr}
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  storageClassName: rook-cephfs
  volumeMode: Filesystem