apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvc-869cee33-fe70-46ee-a6d3-24428957a82b-{user-zkr} # modify 
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 100Gi
  csi:
    driver: rook-ceph.cephfs.csi.ceph.com
    nodeStageSecretRef:
      name: rook-csi-cephfs-node-user # modify 
      namespace: rook-ceph
    volumeAttributes:
      clusterID: rook-ceph
      fsName: cephfs
      pool: cephfs-replicated
      staticVolume: "true" # add 
      storage.kubernetes.io/csiProvisionerIdentity: 1695489697428-6083-rook-ceph.cephfs.csi.ceph.com
      subvolumeName: csi-vol-89a571d2-8d60-48a3-87a9-517c0e023d42
      subvolumePath: /volumes/csi/csi-vol-89a571d2-8d60-48a3-87a9-517c0e023d42/3007dc86-9bff-4603-9b4a-aa67be26412b
      rootPath: /volumes/csi/csi-vol-89a571d2-8d60-48a3-87a9-517c0e023d42/3007dc86-9bff-4603-9b4a-aa67be26412b  # add 
    volumeHandle: 0001-0009-rook-ceph-0000000000000002-89a571d2-8d60-48a3-87a9-517c0e023d42-{user-zkr} # modify 
  persistentVolumeReclaimPolicy: Retain
  storageClassName: rook-cephfs
  volumeMode: Filesystem
