apiVersion: v1
kind: Secret
data:
  userID: Y3NpLWNlcGhmcy1ub2Rl
  userKey: QVFEWEhnOWwxb2J0R3hBQWFkVnJsUWdYMHA4Z2NZQkt2bkprcFE9PQ==
metadata:
  name: rook-csi-cephfs-node-user
  namespace: rook-ceph
type: kubernetes.io/rook