apiVersion: aisystem.k8s.io/v1alpha1
kind: AIJob
metadata:
  name: pytorch-tcp-dist-mnist
  namespace: user-zhuangkr
spec:
  replicas: 1
  resourceRequest:
    cpu: 10
    nvidia.com/gpu: 1
    memory: 100Gi
  template:
    metadata:
      name: pytorch-tcp-dist-mnist-pod
      namespace: user-zhuangkr
    spec:
      containers:
      - image: gcr.io/kubeflow-ci/pytorch-dist-mnist_test:1.0
        name: main
        ports:
        - containerPort: 23456
          name: pytorchjob-port
        resources:
          cpu: 10
          nvidia.com/gpu: 1
          memory: 100Gi
