apiVersion: aisystem.k8s.io/v1alpha1
kind: AIJob
metadata:
  name: cnn-training
  namespace: user-zhuangkr
spec:
  image: gcr.io/kubeflow-ci/pytorch-dist-mnist_test:1.0
  slo: high
  kind: pytorch
  workingDir: /home/zhuangkr/cnn
  envs:
  - name: BATCH_SIZE
    value: 10
  - name: EPOCHS
    value: 200
  script: -|
    echo "Begin training cnn"
    echo "batch_size=$BATCH_SIZE"
    python3 cnn.py --batch_size=$BATCH_SIZE --ephocs=$EPOCHS
  resources:
    request:
      cpu: 10
      gpu: 1
      memory: 100Gi
status:
  phase: Running



  
