apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-proxy
  namespace: crater
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      nodeSelector: {{ .Values.nodeSelector | toYaml | nindent 8 }}
      tolerations: {{ .Values.tolerations | toYaml | nindent 8 }}
      containers:
      - name: nginx
        image: ***REMOVED***/docker.io/library/nginx:1.27.3-bookworm
        ports:
        - containerPort: 80
        volumeMounts:
        - name: config-volume
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
      volumes:
      - name: config-volume
        configMap:
          name: grafana-proxy-conf
