apiVersion: v1
kind: ServiceAccount
metadata:
  name: old-be
  namespace: crater
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: old-be
  namespace: crater
  labels:
    app: old-be
spec:
  replicas: 1
  selector:
    matchLabels:
      app: old-be
  template:
    metadata:
      labels:
        app: old-be
    spec:
      containers:
        - name: old-be-container
          image: ***REMOVED***/crater/web-backend@sha256:c163ee5f35267e43c6427a103efebb4d6af866176dce673bdefd0d934f738d34
          imagePullPolicy: IfNotPresent
          command:
            - /controller
            - --config-file=/etc/config/config.yaml
          volumeMounts:
            - name: backend-conf
              mountPath: /etc/config/config.yaml
              subPath: config.yaml
          resources:
            limits:
              cpu: 1000m
              memory: 2Gi
            requests:
              cpu: 100m
              memory: 128Mi
      serviceAccountName: old-be
      volumes:
        - name: backend-conf
          configMap:
            name: old-be-config
            items:
              - key: config.yaml
                path: config.yaml
---
apiVersion: v1
kind: Service
metadata:
  name: old-be-svc
  namespace: crater
spec:
  selector:
    app: old-be
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8088
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: old-be-cluster-role
rules:
  - apiGroups:
      - "*"
    resources:
      - "*"
    verbs:
      - "*"
  - apiGroups:
      - apps
      - extensions
    resources:
      - "*"
    verbs:
      - "*"
  - apiGroups:
      - policy
    resources:
      - poddisruptionbudgets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - "storage.k8s.io"
    resources:
      - "*"
    verbs:
      - "*"
  - apiGroups:
      - "coordination.k8s.io"
    resources:
      - leases
    verbs:
      - create
      - get
      - list
      - update
  - apiGroups:
      - "events.k8s.io"
    resources:
      - "*"
    verbs:
      - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: old-be-cluster-role-binding
subjects:
  - kind: ServiceAccount
    name: old-be
    namespace: crater
roleRef:
  kind: ClusterRole
  name: old-be-cluster-role
  apiGroup: rbac.authorization.k8s.io
