apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: crater-web-frontend-ingress
  namespace: {{ .Release.Namespace }}
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - {{ .Values.web.ingress.host }}
      secretName: crater-tls-secret
  rules:
    - host: {{ .Values.web.ingress.host }}
      http:
        paths:
          - path: /website
            pathType: Prefix
            backend:
              service:
                name: crater-website-svc
                port:
                  number: 80
          - path: /
            pathType: Prefix
            backend:
              service:
                name: crater-web-frontend-svc
                port:
                  number: 80
