apiVersion: v1
kind: ConfigMap
metadata:
  name: crater-cronjob-config
  namespace: {{ .Release.Namespace }}
  labels:
    crater.raids-lab.io/component: cronjob
data:
  USERNAME: {{ .Values.web.cronjob.config.USERNAME }}
  PASSWORD: {{ .Values.web.cronjob.config.PASSWORD }}
  HOST: {{ .Values.web.cronjob.config.HOST }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: crater-cronjob-scripts
  namespace: {{ .Release.Namespace }}
  labels:
    crater.raids-lab.io/component: cronjob
data:
  token.sh: |-
    #!/bin/sh
    response=$(curl -s -X POST \
      "https://${HOST}/api/auth/login" \
      -H 'accept: application/json' \
      -H 'Content-Type: application/json' \
      -d "{
      \"auth\": \"normal\",
      \"password\": \"${PASSWORD}\",
      \"username\": \"${USERNAME}\"
    }")

    accessToken=$(echo "$response" | jq -r '.data.accessToken')
    echo "$accessToken"
  
  clean-long-time-job.sh: |-
    #!/bin/sh
    accessToken=$(sh /scripts/token.sh)

    echo "清理长时间任务..."
    curl -X DELETE \
      "https://${HOST}/api/v1/admin/operations/cleanup?batchDays=${BATCH_DAYS}&interactiveDays=${INTERACTIVE_DAYS}" \
      -H 'accept: application/json' \
      -H "Authorization: Bearer ${accessToken}"

  clean-low-gpu-util-job.sh: |-
    #!/bin/sh
    accessToken=$(sh /scripts/token.sh)

    echo "清理GPU低利用率任务..."
    curl -X DELETE \
      "https://${HOST}/api/v1/admin/operations/auto?timeRange=${TIME_RANGE}&waitTime=${WAIT_TIME}&util=${UTIL}" \
      -H 'accept: application/json' \
      -H "Authorization: Bearer ${accessToken}"

  clean-waiting-jupyter.sh: |-
    #!/bin/sh
    accessToken=$(sh /scripts/token.sh)

    echo "清理等待的Jupyter任务..."
    curl -X DELETE \
      "https://${HOST}/api/v1/admin/operations/waiting/jupyter?waitMinitues=${JUPYTER_WAIT_MINUTES}" \
      -H 'accept: application/json' \
      -H "Authorization: Bearer ${accessToken}"
