apiVersion: v1
kind: ConfigMap
metadata:
  name: cleanup-config
  namespace: {{ .Release.Namespace }}
data: {{ toYaml .Values.web.cronjob.config | nindent 2 }}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: delete-operation-job
  namespace: {{ .Release.Namespace }}
spec:
  schedule: {{ .Values.web.cronjob.schedule }}
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cleanup
            image: {{ .Values.web.cronjob.image }}
            imagePullPolicy: IfNotPresent
            envFrom:
            - configMapRef:
                name: cleanup-config
          restartPolicy: OnFailure


