apiVersion: v1
kind: ConfigMap
metadata:
  name: cleanup-config
  namespace: crater
data:
  USERNAME: "***REMOVED***"
  PASSWORD: "***REMOVED***"
  BATCH_DAYS: "5"
  INTERACTIVE_DAYS: "5"
  TIME_RANGE: "90"
  WAIT_TIME: "30"
  UTIL: "0"
  HOST: ***REMOVED***
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: delete-operation-job
  namespace: crater
spec:
  schedule: 0,30 * * * *
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cleanup
            image: ***REMOVED***/clean:v3
            envFrom:
            - configMapRef:
                name: cleanup-config
          restartPolicy: OnFailure


