---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - aisystem.github.com
  resources:
  - aijobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - aisystem.github.com
  resources:
  - aijobs/finalizers
  verbs:
  - update
- apiGroups:
  - aisystem.github.com
  resources:
  - aijobs/status
  verbs:
  - get
  - patch
  - update
