apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: home-lyl
  namespace: jupyter
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  storageClassName: rook-cephfs
  volumeMode: Filesystem