enableLeaderElection: false
leaderElectionID: ***REMOVED***
enableProfiling: true
prometheusAPI: "http://10.8.0.16:31110"
profilingTimeout: 120
dbHost: ***REMOVED***
dbPort: 30306
dbUser: root
dbPassword: buaak8sportal@2023mysql
dbName: ai_portal
dbCharset: utf8mb4
dbConnTimeout: 10
serverAddr: :8098
metricsAddr: :8090
probeAddr: :8091
monitoringPort: 0
postgres:
  host: ***REMOVED***
  port: 30432
  dbname: crater
  user: postgres
  password: ***REMOVED***
  sslmode: require
  TimeZone: Asia/Shanghai
workspace:
  namespace: crater-workspace
  pvcName: crater-storage
  ingressName: crater-jobs-ingress
  imageNameSpace: crater-images
act:
  image:
    registryServer: ***REMOVED***
    registryUser: ***REMOVED***
    registryPass: ***REMOVED***
    registryProject: crater-images
  auth:
    userName: ***REMOVED***
    password: ***REMOVED***
    address: ***REMOVED***
    searchDN: OU=Lab,OU=ACT,DC=lab,DC=act,DC=buaa,Dc=edu,DC=cn
