enableLeaderElection: false
leaderElectionID: 1ca428e5.training-operator.kubeflow.org
prometheusAPI: http://***REMOVED***:31110
serverAddr: :8098
metricsAddr: :8090
probeAddr: :8091
monitoringPort: 0
jycache: true
host: crater.***REMOVED***
postgres:
  host: ***REMOVED***
  port: 30432
  dbname: crater
  user: postgres
  password: ***REMOVED***
  sslmode: disable
  TimeZone: Asia/Shanghai
userSpacePrefix: ***REMOVED***
accountSpacePrefix: crater-accounts
publicSpacePrefix: ***REMOVED***
workspace:
  namespace: crater-workspace
  rwxpvcName: crater-storage
  roxpvcName: crater-rox-storage
  ingressName: crater-jobs-ingress
  imageNameSpace: crater-images
act:
  strictRegisterMode: true
  uidServerURL: http://192.168.5.59:5000/get_user_id
  image:
    registryServer: ***REMOVED***
    registryUser: ***REMOVED***
    registryPass: ***REMOVED***
    registryProject: crater
    registryAdmin: admin
    registryAdminPass: ***REMOVED***
  openAPI:
    url: ***REMOVED***
    chameleonKey: ***REMOVED***
    accessToken: ***REMOVED***
  auth:
    userName: ***REMOVED***
    password: ***REMOVED***
    address: ***REMOVED***
    searchDN: OU=Lab,OU=ACT,DC=lab,DC=act,DC=buaa,Dc=edu,DC=cn
  smtp:
    host: ***REMOVED***
    port: 25
    user: notify
    password: ***REMOVED***
    notify: notify@***REMOVED***
schedulerPlugins:
  aijob:
    aijobEn: true
    enableProfiling: true
    profilingTimeout: 120
  spjob:
    spjobEn: true
    predictionServiceAddress: ***REMOVED***
dindArgs:
  buildkitImage: ***REMOVED***/user-huangsy/buildkit/buildctl:v0.18.2
  nerdctlImage: ***REMOVED***/nerdctl:2.0.1-retry
