enableLeaderElection: false
leaderElectionID: ***REMOVED***
enableProfiling: true
prometheusAPI: ***REMOVED***
profilingTimeout: 120
dbHost: ***REMOVED***
dbPort: 30306
dbUser: root
dbPassword: buaak8sportal@2023mysql
dbName: ai_portal
dbCharset: utf8mb4
dbConnTimeout: 10
serverAddr: :8098
metricsAddr: :8090
probeAddr: :8091
monitoringPort: 0
postgres:
  host: ***REMOVED***
  port: 30432
  dbname: crater
  user: postgres
  password: ***REMOVED***
  sslmode: require
  TimeZone: Asia/Shanghai
