imagePullSecretName: "aliyun-docker-registry"
accountSpacePrefix: crater-accounts
act:
  auth:
    accessTokenSecret: access_token_secret
    address: ***REMOVED***
    password: ***REMOVED***
    refreshTokenSecret: refresh_token_secret
    searchDN: OU=Lab,OU=ACT,DC=lab,DC=act,DC=buaa,Dc=edu,DC=cn
    userName: ***REMOVED***
  image:
    registryAdmin: ***REMOVED***
    registryAdminPass: ***REMOVED***
    registryPass: ***REMOVED***
    registryProject: crater-harbor
    registryServer: ***REMOVED***
    registryUser: ***REMOVED***
  openAPI:
    accessToken: ***REMOVED***
    chameleonKey: ***REMOVED***
    url: ***REMOVED***
  smtp:
    host: ***REMOVED***
    notify: notify@***REMOVED***
    password: ***REMOVED***
    port: 25
    user: notify
  strictRegisterMode: false
  uidServerURL: http://192.168.5.59:5000/get_user_id
dindArgs:
  buildkitImage: ***REMOVED***/crater-harbor/buildkit/buildctl:v0.18.2
  envdImage: ***REMOVED***/crater-harbor/envd-build-frontend:v1.2.0
  nerdctlImage: ***REMOVED***/crater-harbor/nerdctl:2.0.1-retry
enableLeaderElection: false
host: crater.local
leaderElectionID: 1ca428e5.training-operator.kubeflow.org
metricsAddr: :8080
monitoringPort: 9443
postgres:
  TimeZone: Asia/Shanghai
  dbname: crater
  host: localhost
  password: ***REMOVED***
  port: 5432
  sslmode: disable
  user: crater
probeAddr: :8081
prometheusAPI: https://cn-beijing.arms.aliyuncs.com:9443/api/v1/prometheus/d1e7bb1bf74ce15dba9f79c88059/1918744802268151/c131b04e568ee46759d88fa332fb7fdc4/cn-beijing
publicSpacePrefix: ***REMOVED***
schedulerPlugins:
  aijob:
    aijobEn: true
    enableProfiling: true
    profilingTimeout: 120
  spjob:
    predictionServiceAddress: http://resource-analyze-svc.kube-gpu-sparse:80
    spjobEn: true
serverAddr: :8088
tlsForwardSecretName: crater-tls-forward-secret
tlsSecretName: crater-tls-secret
userSpacePrefix: ***REMOVED***
workspace:
  imageNameSpace: crater-images
  ingressName: crater-jobs-ingress
  namespace: crater-workspace
  roxpvcName: crater-rw-storage
  rwxpvcName: crater-rw-storage
