enableProfiling: true
prometheusAPI: ***REMOVED***
profilingTimeout: 120
dbHost: 10.1.167.230
dbPort: 3306
dbUser: root
dbPassword: buaak8sportal@2023mysql
dbName: ai_portal
dbCharset: utf8mb4
dbConnTimeout: 10
serverAddr: :8098
metricsAddr: :8090
probeAddr: :8091
monitoringPort: 0
