enableLeaderElection: false
leaderElectionID: 1ca428e5.training-operator.kubeflow.org
enableProfiling: true
prometheusAPI: http://***REMOVED***:31110
profilingTimeout: 120
serverAddr: :8098
metricsAddr: :8090
probeAddr: :8091
monitoringPort: 0
jycache: true
host: ***REMOVED***
postgres:
  host: ***REMOVED***
  port: 31052
  dbname: crater
  user: crater
  password: ***REMOVED***
  sslmode: disable
  TimeZone: Asia/Shanghai
userSpacePrefix: ***REMOVED***
accountSpacePrefix: crater-accounts
publicSpacePrefix: ***REMOVED***
workspace:
  namespace: crater-workspace
  rwxpvcName: crater-rw-storage
  roxpvcName: crater-ro-storage
  ingressName: crater-jobs-ingress
  imageNameSpace: crater-images
act:
  image:
    registryServer: ***REMOVED***
    registryUser: ***REMOVED***
    registryPass: ***REMOVED***
    registryProject: crater
    registryAdmin: admin
    registryAdminPass: ***REMOVED***
  openAPI:
    url: ***REMOVED***
    chameleonKey: ***REMOVED***
    accessToken: ***REMOVED***
  auth:
    userName: ***REMOVED***
    password: ***REMOVED***
    address: ***REMOVED***
    searchDN: OU=Lab,OU=ACT,DC=lab,DC=act,DC=buaa,Dc=edu,DC=cn
  smtp:
    host: ***REMOVED***
    port: 25
    user: notify
    password: ***REMOVED***
    notify: notify@***REMOVED***
wpsRobot:
  webhookAddress: https://xz.wps.cn/api/v1/webhook/send?key=4dd9cd4970e225491cfefcfafe7ee2e3
schedulerPlugins:
  aijob:
    aijobEn: false
  spjob:
    spjobEn: false
    predictionServiceAddress: ***REMOVED***
dindArgs:
  buildkitImage: ***REMOVED***/user-huangsy/buildkit/buildctl:v0.18.2
  nerdctlImage: ***REMOVED***/nerdctl:2.0.1-retry
