enableLeaderElection: false
leaderElectionID: ***REMOVED***
enableProfiling: true
prometheusAPI: ***REMOVED***
profilingTimeout: 120
serverAddr: :8088
metricsAddr: :8080
probeAddr: :8081
monitoringPort: 9443
postgres:
  host: pscluster-nodeport.crater
  port: 5432
  dbname: crater
  user: postgres
  password: ***REMOVED***
  sslmode: disable
  TimeZone: Asia/Shanghai
workspace:
  namespace: crater-workspace
  rwxpvcName: crater-rw-storage
  roxpvcName: crater-ro-storage
  ingressName: crater-jobs-ingress
  imageNameSpace: crater-images
act:
  image:
    registryServer: ***REMOVED***
    registryUser: ***REMOVED***
    registryPass: ***REMOVED***
    registryProject: crater
    registryAdmin: admin
    registryAdminPass: ***REMOVED***
  openAPI:
    url: ***REMOVED***
    chameleonKey: ***REMOVED***
    accessToken: ***REMOVED***
  auth:
    userName: ***REMOVED***
    password: ***REMOVED***
    address: ***REMOVED***
    searchDN: OU=Lab,OU=ACT,DC=lab,DC=act,DC=buaa,Dc=edu,DC=cn
  smtp:
    host: ***REMOVED***
    port: 25
    user: notify
    password: ***REMOVED***
    notify: ***REMOVED***
wpsRobot:
  webhookAddress: ***REMOVED***
schedulerPlugins:
  aijob:
    aijobEn: false
  spjob:
    spjobEn: false
    predictionServiceAddress: "***REMOVED***"
dindArgs:
  buildkitImage: "***REMOVED***/user-huangsy/buildkit/buildctl:v0.18.2"
  nerdctlImage: "***REMOVED***/nerdctl:2.0.1-retry"
