enableLeaderElection: false
leaderElectionID: ***REMOVED***
enableProfiling: true
prometheusAPI: ***REMOVED***
profilingTimeout: 120
dbHost: mycluster.jupyter
dbPort: 3306
dbUser: root
dbPassword: buaak8sportal@2023mysql
dbName: ai_portal
dbCharset: utf8mb4
dbConnTimeout: 10
serverAddr: :8088
metricsAddr: :8080
probeAddr: :8081
monitoringPort: 9443
postgres:
  host: postgres-cluster.crater
  port: 5432
  dbname: crater
  user: postgres
  password: ***REMOVED***
  sslmode: require
  TimeZone: Asia/Shanghai
workspace:
  namespace: crater-workspace
  pvcName: crater-storage
  ingressName: crater-jobs-ingress
act:
  image:
    registryServer: ***REMOVED***
    registryUser: ***REMOVED***
    registryPass: ***REMOVED***
    registryProject: crater-images
  auth:
    userName: ***REMOVED***
    password: ***REMOVED***
    address: ***REMOVED***
    searchDN: OU=Lab,OU=ACT,DC=lab,DC=act,DC=buaa,Dc=edu,DC=cn
