enableLeaderElection: false
leaderElectionID: ***REMOVED***
enableProfiling: true
prometheusAPI: "http://8.141.83.224:32618/"
profilingTimeout: 120
dbHost: mycluster.jupyter
dbPort: 3306
dbUser: root
dbPassword: buaak8sportal@2023mysql
dbName: ai_portal
dbCharset: utf8mb4
dbConnTimeout: 10
serverAddr: :8088
metricsAddr: :8080
probeAddr: :8081
monitoringPort: 9443
postgres:
  host: ***REMOVED***
  port: 30841
  dbname: crater
  user: postgres
  password: ***REMOVED***
  sslmode: disable
  TimeZone: Asia/Shanghai
workspace:
  namespace: crater-workspace
  pvcName: crater-storage
  ingressName: crater-jobs-ingress
  imageNameSpace: crater-images
act:
  image:
    registryServer: ***REMOVED***
    registryUser: ***REMOVED***
    registryPass: ***REMOVED***
    registryProject: crater-images
  openAPI:
    url: ***REMOVED***
    chameleonKey: ***REMOVED***
    accessToken: ***REMOVED***
  auth:
    userName: ***REMOVED***
    password: ***REMOVED***
    address: ***REMOVED***
    searchDN: OU=Lab,OU=ACT,DC=lab,DC=act,DC=buaa,Dc=edu,DC=cn
