apiVersion: apps/v1
kind: Deployment
metadata:
  name: webdav-deployment
  namespace: crater-workspace
  labels:
    app: webdav-crater
spec:
  selector:
    matchLabels:
      app: webdav-crater
  replicas: 2
  template:
    metadata:
      labels:
        app: webdav-crater
    spec:
      serviceAccountName: default
      nodeSelector: {{ .Values.nodeSelector | toYaml | nindent 8 }}
      tolerations: {{ .Values.tolerations | toYaml | nindent 8 }}
      containers:
        - name: webdav
          image: {{ .Values.web.storage.image.repository }}:{{ .Values.web.storage.image.tag }}
          imagePullPolicy: {{ .Values.web.storage.image.pullPolicy }}
          resources:
            limits:
              memory: 10Gi
              cpu: "1"
            requests:
              memory: 256Mi
              cpu: "200m"
          ports:
            - containerPort: 7320
          volumeMounts:
            - name: ss-conf
              mountPath: /etc/config.yaml
              subPath: config.yaml
            - name: mypvc
              mountPath: /crater
      volumes:
        - name: mypvc
          persistentVolumeClaim:
            claimName: {{ .Values.storage.rwName }}
        - name: ss-conf
          configMap:
            name: ss-config
            items:
              - key: config.yaml
                path: config.yaml
