{{- if .Values.storage.create -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.backendConfig.workspace.rwxpvcName}}
  namespace: {{ .Values.backendConfig.workspace.namespace}}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.storage.request }}
  storageClassName: {{ .Values.storage.storageClass}}
{{- end -}}