apiVersion: v1
kind: ConfigMap
metadata:
  name: buildkitd-config
  namespace: {{ .Values.backendConfig.workspace.imageNameSpace }}
data:
  buildkitd.toml: |
    debug = true

    [grpc]
      address = [
        "tcp://0.0.0.0:1234", # tcp is for buildctl connections
        "unix:///run/user/1000/buildkit/buildkitd.sock", # non-root socket when running as non-root
      ]

    # config for build history API that stores information about completed build commands
    [history]
      # maxAge is the maximum age of history entries to keep, in seconds.
      maxAge = 345600
      # maxEntries is the maximum number of history entries to keep.
      maxEntries = 100

    [worker.oci]
      rootless = true
      noProcessSandbox = true

      gc = true
      reservedSpace = "{{ .Values.web.buildkit.cache.reservedSpace }}"
      maxUsedSpace = "{{ .Values.web.buildkit.cache.maxUsedSpace }}"
      minFreeSpace = "{{ .Values.web.buildkit.cache.minFreeSpace }}"
      cniPoolSize = 16

      [[worker.oci.gcpolicy]]
        reservedSpace = "{{ .Values.web.buildkit.cache.reservedSpace }}"
        maxUsedSpace = "{{ .Values.web.buildkit.cache.maxUsedSpace }}"
        minFreeSpace = "{{ .Values.web.buildkit.cache.minFreeSpace }}"
        keepDuration = "720h"
        filters = [ "type==source.local", "type==exec.cachemount", "type==source.git.checkout"]
      [[worker.oci.gcpolicy]]
        all = true
        reservedSpace = "{{ .Values.web.buildkit.cache.reservedSpace }}"

    [worker.containerd]
      gc = true
      # gckeepstorage sets storage limit for default gc profile, in MB.
      reservedSpace = "{{ .Values.web.buildkit.cache.reservedSpace }}"
      maxUsedSpace = "{{ .Values.web.buildkit.cache.maxUsedSpace }}"
      minFreeSpace = "{{ .Values.web.buildkit.cache.minFreeSpace }}"
      # maintain a pool of reusable CNI network namespaces to amortize the overhead
      # of allocating and releasing the namespaces
      cniPoolSize = 16

      [[worker.containerd.gcpolicy]]
        reservedSpace = "{{ .Values.web.buildkit.cache.reservedSpace }}"
        maxUsedSpace = "{{ .Values.web.buildkit.cache.maxUsedSpace }}"
        minFreeSpace = "{{ .Values.web.buildkit.cache.minFreeSpace }}"
        keepDuration = "720h"
        filters = [ "type==source.local", "type==exec.cachemount", "type==source.git.checkout"]
      [[worker.containerd.gcpolicy]]
        all = true
        reservedSpace = "{{ .Values.web.buildkit.cache.reservedSpace }}"