apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: buildkit-secret
  namespace: crater-images
data:
  .dockerconfigjson: eyJhdXRocyI6IHsiY3JhdGVyLWhhcmJvci5hY3QuYnVhYS5lZHUuY24iOiB7InVzZXJuYW1lIjogInJvYm90JGNyYXRlci1yb2JvdDIiLCJwYXNzd29yZCI6ICJIc1NwbU4wcXhKc1RiVEl6VEJBYjVhYkRhTFdOM2pPVCJ9fX0=
