apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: buildkit-secret
  namespace: {{ .Values.backendConfig.workspace.imageNameSpace }}
data:
  .dockerconfigjson: {{ .Values.web.buildkit.dockerconfigjson }}
