# This file is used to deploy the backend service to the k8s cluster
apiVersion: v1
kind: ServiceAccount
metadata:
  name: crater-web-backend
  namespace: crater

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: crater-workspace
  name: crater-role
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["create", "get", "list", "watch", "update", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: crater-rolebinding
  namespace: crater-workspace
subjects:
  - kind: ServiceAccount
    name: crater-web-backend
    namespace: crater
roleRef:
  kind: Role
  name: crater-role
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: crater-viewer
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["scheduling.volcano.sh"]
    resources: ["queues"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["apiextensions.k8s.io", "hsy.hsy.crd"]
    resources: ["imagepacks"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]  # 空字符串表示核心 API 组
    resources: ["nodes"]
    verbs: ["get", "list", "watch", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: crater-viewer-binding
subjects:
  - kind: ServiceAccount
    name: crater-web-backend
    namespace: crater
roleRef:
  kind: ClusterRole
  name: crater-viewer
  apiGroup: rbac.authorization.k8s.io
