apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: crater-storage
  namespace: crater-workspace
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Ti
  storageClassName: rook-cephfs
