apiVersion: v1
kind: ConfigMap
metadata:
  name: share-dir
  namespace: ai-portal
data:
  share-dir.yaml: |-
    shareDirs:
    - pvc: dnn-train-data
      namespace: user-wjh
    - pvc: jupyterhub-shared-volume
      namespace: jupyter