apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 31121  # 制定nginx代理的grafana nodePort
  selector:
    app: nginx
