web:
  backend:
    image:
      repository: ***REMOVED***
      tag: "3a1af9bb"
      pullPolicy: "IfNotPresent"
  frontend:
    image:
      repository: ***REMOVED***
      tag: "100f83f1"
      pullPolicy: "IfNotPresent"

backendConfig:
  content: |
    enableLeaderElection: false
    leaderElectionID: ***REMOVED***
    enableProfiling: true
    prometheusAPI: ***REMOVED***
    profilingTimeout: 120
    serverAddr: ":8088"
    metricsAddr: ":8080"
    probeAddr: ":8081"
    monitoringPort: 9443
    postgres:
      host: postgres-cluster.crater
      port: 5432
      dbname: crater
      sslmode: require
      TimeZone: Asia/Shanghai
    workspace:
      namespace: crater-workspace
      pvcName: crater-storage
      ingressName: crater-jobs-ingress
      imageNameSpace: crater-images

# Usage:
# helm install crater ./charts/crater \
# --set-string tls.cert="$(cat path/to/tls.crt)"\
# --set-string tls.key="$(cat path/to/tls.key)"
tls:
  cert: "===hdgddh==="
  key: "==="

storage:
  create: false
  request: 2Ti
  storageClass: "nfs-client"
