web:
  backend:
    image:
      repository: ***REMOVED***
      tag: "37352a97"
      pullPolicy: "IfNotPresent"
  frontend:
    image:
      repository: ***REMOVED***
      tag: "5af85d86"
      pullPolicy: "IfNotPresent"
  storage:
    images:
      repository: ***REMOVED***
      tag: "jg5s886d"
      pullPolicy: "IfNotPresent"

backendConfig:
  content: |
    enableLeaderElection: false
    leaderElectionID: ***REMOVED***
    enableProfiling: true
    prometheusAPI: ***REMOVED***
    profilingTimeout: 120
    serverAddr: :8088
    metricsAddr: :8080
    probeAddr: :8081
    monitoringPort: 9443
    postgres:
      host: ***REMOVED***
      port: 30841
      dbname: crater
      user: postgres
      password: ***REMOVED***
      sslmode: disable
      TimeZone: Asia/Shanghai
    workspace:
      namespace: crater-workspace
      pvcName: crater-storage
      ingressName: crater-jobs-ingress
      imageNameSpace: crater-images
    act:
      image:
        registryServer: ***REMOVED***
        registryUser: ***REMOVED***
        registryPass: ***REMOVED***
        registryProject: crater-images

# Usage:
# helm install crater ./charts/crater \
# --set-string tls.cert="$(cat path/to/tls.crt)"\
# --set-string tls.key="$(cat path/to/tls.key)"
tls:
  cert: "===hdgddh==="
  key: "==="

storage:
  create: false
  request: 2Ti
  storageClass: "nfs-client"
