apiVersion: v1
kind: Pod
metadata:
  generateName: pytorch-training-
  namespace: user-zkr
  # ownerReferences:
  # - apiVersion: apps/v1
  #   blockOwnerDeletion: true
  #   controller: true
  #   kind: AIJob
  #   name: deployment-yolo-58bbdbc7f6
  #   uid: 2521f78b-7ef0-46db-880a-b23bb5dfb2e2
spec:
  containers:
  - name: main
    command:
    - /bin/sh
    - -c
    - python resnet18.py
    workingDir: /home/zkr/gpu_bench
    image: pytorch/pytorch:latest
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        nvidia.com/gpu: "1"
      requests:
        nvidia.com/gpu: "1"
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /dev/shm
      name: cache-volume
    - mountPath: /home/zkr
      name: home
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeSelector:
    kubernetes.io/hostname: scse-dell-08
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Never
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - emptyDir:
      medium: Memory
      sizeLimit: 15Gi
    name: cache-volume
  - hostPath:
      type: DirectoryOrCreate
      path: /home/zkr
    name: home
