# nginx-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: crater-website
  namespace: {{ .Release.Namespace }}
  labels:
    app: crater-website
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crater-website
  template:
    metadata:
      labels:
        app: crater-website
    spec:
      containers:
        - name: crater-website-container
          image: ***REMOVED***/website:v0.1.4
          resources:
            limits:
              cpu: 4000m
              memory: 4Gi
            requests:
              cpu: 100m
              memory: 128Mi
          ports:
            - containerPort: 8888
              name: docusaurus
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /website
              port: 8888
            initialDelaySeconds: 20
            periodSeconds: 10
      nodeSelector: {{ .Values.nodeSelector | toYaml | nindent 8 }}
      tolerations: {{ .Values.tolerations | toYaml | nindent 8 }}