apiVersion: v1
kind: ConfigMap
metadata:
  name: custom-start-configmap
  namespace: {{ .Values.backendConfig.workspace.namespace}}
data:
  start.sh: |
    #!/bin/bash
    set -euo pipefail  # Strict error handling: undefined vars and pipe errors
    # ========== User & Group Configuration ==========
    # Validate required environment variables
    : "${NB_USER:?NB_USER must be set}"
    : "${NB_UID:?NB_UID must be set}"
    : "${NB_GID:?NB_GID must be set}"
    # Create group if not exists
    if ! getent group "${NB_GID}" &>/dev/null; then
        groupadd --force --gid "${NB_GID}" --non-unique "${NB_GROUP:-${NB_USER}}"
    fi
    # Create user if not exists
    if ! id "${NB_USER}" &>/dev/null; then
        useradd --no-log-init \
                --home "/home/${NB_USER}" \
                --shell /bin/zsh \
                --uid "${NB_UID}" \
                --gid "${NB_GID}" \
                --groups 100 \
                "${NB_USER}"
    else
        echo "User ${NB_USER} already exists, will not recreate"
    fi
    # ========== Directory & Permissions ==========
    # Ensure proper home directory setup
    mkdir -p "/home/${NB_USER}"
    chown "${NB_UID}:${NB_GID}" "/home/${NB_USER}"
    chmod 755 "/home/${NB_USER}"  # Standard directory permissions
    # Configure sudo access
    SUDOERS_FILE="/etc/sudoers.d/nopasswd-${NB_USER}"
    if [ ! -f "${SUDOERS_FILE}" ]; then
        echo "${NB_USER} ALL=(ALL) NOPASSWD:ALL" > "${SUDOERS_FILE}"
        chmod 440 "${SUDOERS_FILE}"  # Secure sudoers file permissions
    fi
    # ========== Shell Environment ==========
    # Initialize zsh configuration
    ZSHRC_FILE="/home/${NB_USER}/.zshrc"
    if [ ! -f "${ZSHRC_FILE}" ]; then
        touch "${ZSHRC_FILE}"
        chown "${NB_UID}:${NB_GID}" "${ZSHRC_FILE}"
    fi
    # ========== Command Execution ==========
    # Execute with minimal preserved environment
    if [ $# -gt 0 ]; then
        # If arguments passed, execute them as commands
        exec sudo --preserve-env --set-home --user "${NB_USER}" \
            LD_LIBRARY_PATH="${LD_LIBRARY_PATH:-}" \
            "$@"
    else
        # Otherwise just switch user
        exec sudo --preserve-env --set-home --user "${NB_USER}" \
            LD_LIBRARY_PATH="${LD_LIBRARY_PATH:-}" \
            /bin/zsh
    fi
