apiVersion: v1
kind: ConfigMap
metadata:
  name: jupyter-start-configmap
  namespace: crater-workspace
data:
  start.sh: |
    #!/bin/bash
    set -e
    # 判断用户是否已存在
    if id "${NB_USER}" &>/dev/null; then
        echo "User ${NB_USER} already exists, will not recreate"
    else
        # Add user
        groupadd --force --gid "${NB_GID}" --non-unique "${NB_GROUP:-${NB_USER}}"
        useradd --no-log-init --home "/home/${NB_USER}" --shell /bin/bash --uid "${NB_UID}" --gid "${NB_GID}" --groups 100 "${NB_USER}"
    fi
    # Ensuring home dir is owned by user
    chown "${NB_UID}:${NB_GID}" "/home/${NB_USER}"
    # Granting user passwordless sudo rights
    echo "${NB_USER} ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers.d/added-by-start-script
    exec sudo --preserve-env --set-home --user "${NB_USER}" LD_LIBRARY_PATH="${LD_LIBRARY_PATH}" PATH="${PATH}" PYTHONPATH="${PYTHONPATH:-}" "$@"