apiVersion: v1
kind: ConfigMap
metadata:
  name: jupyter-start-configmap
  namespace: crater-workspace
data:
  start.sh: |
    #!/bin/bash

    set -e

    # Add user
    NB_GID=100
    groupadd --force --gid "${NB_GID}" --non-unique "${NB_GROUP:-${NB_USER}}"
    useradd --no-log-init --home "/home/${NB_USER}" --shell /bin/bash --uid "${NB_UID}" --gid "${NB_GID}" --groups 100 "${NB_USER}"

    # Ensuring home dir is owned by user
    chown "${NB_UID}:${NB_GID}" "/home/${NB_USER}"

    # Granting user passwordless sudo rights
    echo "${NB_USER} ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers.d/added-by-start-script
